In [2]:
%pylab notebook
import numpy as np
import numpy.linalg as la
from readonly.PageRankFunctions import *
np.set_printoptions(suppress=True)

Populating the interactive namespace from numpy and matplotlib


In [27]:
L = np.array([[0,   1/2, 1/3, 0, 0,   0 ],
              [1/3, 0,   0,   0, 1/2, 1/2 ],
              [1/3, 1/2, 0,   1, 0,   0 ],
              [1/3, 0,   1/3, 0, 1/2, 0 ],
              [0,   0,   0,   0, 0,   1/2 ],
              [0,   0,   1/3, 0, 0,   0 ]])

In [28]:
eVals, eVecs = la.eig(L)

print("Values: ", eVals)
print("Vectors: ", eVecs)

Values:  [ 1.       +0.j         -0.5209251+0.12753039j -0.5209251-0.12753039j
  0.0209251+0.38003382j  0.0209251-0.38003382j -0.       +0.j        ]
Vectors:  [[-0.38996632+0.j          0.62645101+0.j          0.62645101-0.j
  -0.19173982-0.35855615j -0.19173982+0.35855615j  0.80178373+0.j        ]
 [-0.30724619+0.j         -0.39493419-0.02793696j -0.39493419+0.02793696j
   0.50193799+0.j          0.50193799-0.j          0.        +0.j        ]
 [-0.70902968+0.j         -0.38660087+0.28158007j -0.38660087-0.28158007j
  -0.35615312-0.24111132j -0.35615312+0.24111132j  0.        +0.j        ]
 [-0.42541781+0.j          0.15413017-0.18201701j  0.15413017+0.18201701j
  -0.10287781-0.02087679j -0.10287781+0.02087679j -0.26726124+0.j        ]
 [-0.11817161+0.j         -0.27405524+0.04122697j -0.27405524-0.04122697j
   0.37682428+0.32071053j  0.37682428-0.32071053j -0.53452248+0.j        ]
 [-0.23634323+0.j          0.27500912-0.11285308j  0.27500912+0.11285308j
  -0.22799152+0.29983374j -0.

In [29]:
order = np.absolute(eVals).argsort()[::-1]

eVals = eVals[order]
print("Values: ", eVals)

eVecs = eVecs[:,order]
print("Vectors: ", eVecs)

Values:  [ 1.       +0.j         -0.5209251-0.12753039j -0.5209251+0.12753039j
  0.0209251-0.38003382j  0.0209251+0.38003382j -0.       +0.j        ]
Vectors:  [[-0.38996632+0.j          0.62645101-0.j          0.62645101+0.j
  -0.19173982+0.35855615j -0.19173982-0.35855615j  0.80178373+0.j        ]
 [-0.30724619+0.j         -0.39493419+0.02793696j -0.39493419-0.02793696j
   0.50193799-0.j          0.50193799+0.j          0.        +0.j        ]
 [-0.70902968+0.j         -0.38660087-0.28158007j -0.38660087+0.28158007j
  -0.35615312+0.24111132j -0.35615312-0.24111132j  0.        +0.j        ]
 [-0.42541781+0.j          0.15413017+0.18201701j  0.15413017-0.18201701j
  -0.10287781+0.02087679j -0.10287781-0.02087679j -0.26726124+0.j        ]
 [-0.11817161+0.j         -0.27405524-0.04122697j -0.27405524+0.04122697j
   0.37682428-0.32071053j  0.37682428+0.32071053j -0.53452248+0.j        ]
 [-0.23634323+0.j          0.27500912+0.11285308j  0.27500912-0.11285308j
  -0.22799152-0.29983374j -0.

In [34]:
r = eVecs[:, 0]
print(r)

100 * np.real(r / np.sum(r))

[-0.38996632+0.j -0.30724619+0.j -0.70902968+0.j -0.42541781+0.j
 -0.11817161+0.j -0.23634323+0.j]


array([17.83783784, 14.05405405, 32.43243243, 19.45945946,  5.40540541,
       10.81081081])

In [88]:
r = 100 * np.ones(6) / 6
r

array([16.66666667, 16.66666667, 16.66666667, 16.66666667, 16.66666667,
       16.66666667])

In [83]:
r = L @ r
r

array([17.83783784, 14.05405405, 32.43243243, 19.45945946,  5.40540541,
       10.81081081])

In [91]:
r = 100 * np.ones(6) / 6

iteration = 0
prevR = r

r = L @ r

while la.norm(r - prevR) > 1e-7:
    prevR = r
    r = L @ r
    iteration += 1
    
print("r now is: ", r)
print("Took ", iteration, " iterations")

r now is:  [17.83783782 14.05405406 32.43243246 19.45945945  5.40540542 10.8108108 ]
Took  31  iterations


In [100]:
n = 4
d = 0.5
dampM = ((1 - d) / n) * np.ones((n, n))

dampM

array([[0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125]])

In [129]:
L = np.array([[0.1, 0.1, 0.8],
              [0.8, 0.1, 0.1],
              [0.1, 0.8, 0.1]])
print("L:\n", L)

r = 1/3 * np.ones(3)

rPrev = r
r = L @ r

while la.norm(r - rPrev) > 1e-5:
    rPrev = r
    r = L @ r
    
print(r)

w, v = la.eig(L)
print(w)
print(v)



L:
 [[0.1 0.1 0.8]
 [0.8 0.1 0.1]
 [0.1 0.8 0.1]]
[0.33333333 0.33333333 0.33333333]
[ 1.  +0.j         -0.35+0.60621778j -0.35-0.60621778j]
[[ 0.57735027+0.j  -0.28867513+0.5j -0.28867513-0.5j]
 [ 0.57735027+0.j   0.57735027+0.j   0.57735027-0.j ]
 [ 0.57735027+0.j  -0.28867513-0.5j -0.28867513+0.5j]]


In [131]:
L2 = np.array([[0.1, 0.7, 0.1, 0.1 ],
            [0.7, 0.1, 0.1, 0.1],
            [0.1, 0.1, 0.1, 0.7],
            [0.1, 0.1, 0.7, 0.1]])

w, v = la.eig(L2)
print(w)
print(v)

la.det(L2)

[-0.6  0.6  1.  -0.6]
[[ 0.70710678 -0.5        -0.5        -0.05633503]
 [-0.70710678 -0.5        -0.5         0.05633503]
 [ 0.          0.5        -0.5        -0.70485911]
 [ 0.          0.5        -0.5         0.70485911]]


0.21599999999999997

In [135]:
L = np.array([[0,   1/2, 1/3, 0, 0,   0 ],
              [1/3, 0,   0,   0, 1/2, 1/2 ],
              [1/3, 1/2, 0,   1, 0,   0 ],
              [1/3, 0,   1/3, 0, 1/2, 0 ],
              [0,   0,   0,   0, 0,   1/2 ],
              [0,   0,   1/3, 0, 0,   0 ]])

eVals, eVecs = la.eig(L)
print(eVals)
print(eVecs)

print(la.norm(eVals))

[ 1.       +0.j         -0.5209251+0.12753039j -0.5209251-0.12753039j
  0.0209251+0.38003382j  0.0209251-0.38003382j -0.       +0.j        ]
[[-0.38996632+0.j          0.62645101+0.j          0.62645101-0.j
  -0.19173982-0.35855615j -0.19173982+0.35855615j  0.80178373+0.j        ]
 [-0.30724619+0.j         -0.39493419-0.02793696j -0.39493419+0.02793696j
   0.50193799+0.j          0.50193799-0.j          0.        +0.j        ]
 [-0.70902968+0.j         -0.38660087+0.28158007j -0.38660087-0.28158007j
  -0.35615312-0.24111132j -0.35615312+0.24111132j  0.        +0.j        ]
 [-0.42541781+0.j          0.15413017-0.18201701j  0.15413017+0.18201701j
  -0.10287781-0.02087679j -0.10287781+0.02087679j -0.26726124+0.j        ]
 [-0.11817161+0.j         -0.27405524+0.04122697j -0.27405524-0.04122697j
   0.37682428+0.32071053j  0.37682428-0.32071053j -0.53452248+0.j        ]
 [-0.23634323+0.j          0.27500912-0.11285308j  0.27500912+0.11285308j
  -0.22799152+0.29983374j -0.22799152-0.29983374